language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

dist:
    - trusty
    - xenial
    - bionic

addons:
  apt:
    packages:
      libssl-dev

install:
  - wget "https://raw.githubusercontent.com/baresip/baresip/master/test/ccheck.py"

script: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        make EXTRA_CFLAGS=-Werror CCACHE=;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        make EXTRA_CFLAGS="-I/usr/local/opt/openssl/include -Werror" EXTRA_LFLAGS="-L/usr/local/opt/openssl/lib" CCACHE=;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python3 ccheck.py ; fi
