language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

jobs:                                                                                                                                                                                         
  include:
      - os: linux
        stage: ccheck
        addons:
          apt:
            update: false
        script:
          - wget "https://raw.githubusercontent.com/baresip/baresip/master/test/ccheck.py"
          - python3 ccheck.py
      - name: OpenSSL 1.0.2g
        os: linux
        dist: xenial
        stage: openssl
      - name: OpenSSL 1.1.1f
        os: linux
        dist: focal
        stage: openssl
      - name: macOS 10.15.5
        os: osx
        osx_image: xcode12.0
        stage: openssl
      - name: LibreSSL
        os: linux
        dist: xenial
        script:
          - wget "https://github.com/baresip/ci/releases/download/v0.1/assets.tar.gz"
          - tar -xf assets.tar.gz
          - make EXTRA_CFLAGS="-Iassets/libressl/include -Werror" EXTRA_LFLAGS="-Lassets/libressl" CCACHE=;
        stage: openssl
      - name: OpenSSL 1.1.1g no-deprecated
        os: linux
        dist: xenial
        script:
          - wget "https://github.com/baresip/ci/releases/download/v0.1/assets.tar.gz"
          - tar -xf assets.tar.gz
          - make EXTRA_CFLAGS="-Iassets/openssl/include -Werror" EXTRA_LFLAGS="-Lassets/openssl" CCACHE=;
        stage: openssl


stages:
  - ccheck
  - test
  - openssl

addons:
  apt:
    packages:
      libssl-dev

script: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        make EXTRA_CFLAGS=-Werror CCACHE=;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        cd ..; rm re/libre.so;
        git clone https://github.com/creytiv/rem;
        make -C rem librem.a;
        git clone https://github.com/baresip/retest.git;
        cd retest && make STATIC=1 LIBRE_SO=../re && ./retest -r;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        make EXTRA_CFLAGS="-I/usr/local/opt/openssl/include -Werror" EXTRA_LFLAGS="-L/usr/local/opt/openssl/lib" CCACHE=;
    fi
