language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

jobs:                                                                                                                                                                                         
  include:
      - os: linux
        stage: ccheck
        addons: {}
        script:
          - wget "https://raw.githubusercontent.com/baresip/baresip/master/test/ccheck.py"
          - python3 ccheck.py
      - os: linux
        dist: xenial # OpenSSL 1.0.2g  1 Mar 2016
        stage: openssl
      - os: linux
        dist: focal # OpenSSL 1.1.1f  31 Mar 2020
        stage: openssl
      - os: osx
        osx_image: xcode12.0
        stage: openssl

stages:
  - ccheck
  - test
  - openssl

addons:
  apt:
    packages:
      libssl-dev

script: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        make EXTRA_CFLAGS=-Werror CCACHE=;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        make EXTRA_CFLAGS="-I/usr/local/opt/openssl/include -Werror" EXTRA_LFLAGS="-L/usr/local/opt/openssl/lib" CCACHE=;
    fi
