language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

jobs:                                                                                                                                                                                         
  include:                                                                                                                                                                                    
      - os: linux
        dist: trusty
        stage: openssl
      - os: linux
        dist: bionic
        stage: openssl
      - os: linux
        dist: focal
        stage: openssl
      - os: osx
        osx_image: xcode12.0
        stage: openssl

stages:
  - test
  - openssl

addons:
  apt:
    packages:
      libssl-dev

install:
  - wget "https://raw.githubusercontent.com/baresip/baresip/master/test/ccheck.py"

script: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        make EXTRA_CFLAGS=-Werror CCACHE=;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        make EXTRA_CFLAGS="-I/usr/local/opt/openssl/include -Werror" EXTRA_LFLAGS="-L/usr/local/opt/openssl/lib" CCACHE=;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python3 ccheck.py ; fi
