name: Centos 7

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: centos:7

    strategy:
      matrix:
        compiler: [clang]
        os: [ubuntu-latest]

    env:
      CC: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v2
    - name: install devel tools
      run: |
        yum -y install gcc clang make openssl-devel

    - name: make info
      run: |
        echo "OS: ${{ matrix.os }}"
        echo "--- ${{ matrix.compiler }} DEBUG VERSION ---"
        ${{ matrix.compiler }} - --version
        echo "--- make info ---"
        make info

    - name: make
      run: make EXTRA_CFLAGS=-Werror CCACHE=
