name: Code coverage

on: [push, pull_request]

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: make
      run: | 
        make EXTRA_CFLAGS="-coverage" CCACHE=

    - uses: sreimers/pr-dependency-action@v0.3
      with:
        name: rem
        repo: https://github.com/baresip/rem
        secret: ${{ secrets.GITHUB_TOKEN }}
        working-directory: '../.'

    - uses: sreimers/pr-dependency-action@v0.3
      with:
        name: retest
        repo: https://github.com/baresip/retest.git
        secret: ${{ secrets.GITHUB_TOKEN }}
        working-directory: '../.'

    - name: retest
      run: |
        cd ..
        rm re/libre.so || true
        rm re/libre.dylib || true
        make -C rem librem.a
        cd retest; make EXTRA_LFLAGS="--coverage" && ./retest -a

    - name: gcov
      run: | 
        cd ../re
        gcov build-x86_64/**/*.o
        bash <(curl -s https://codecov.io/bash)